const TYPE_BY_EXTENSION = {
  glb: 'model', gltf: 'model', png: 'texture', jpg: 'texture', jpeg: 'texture', webp: 'texture',
  wav: 'audio', mp3: 'audio', ogg: 'audio', m4a: 'audio',
  json: 'data', csv: 'data', xml: 'data', txt: 'data', md: 'data',
  anim: 'animation', shader: 'shader', vert: 'shader', frag: 'shader',
  ttf: 'font', otf: 'font'
};

export function classifyPackAsset(file) {
  const ext = String(file.name || '').split('.').pop().toLowerCase();
  return TYPE_BY_EXTENSION[ext] || 'data';
}

export function slugify(value) {
  return String(value || 'asset')
    .toLowerCase()
    .replace(/\\/g, '/')
    .split('/').pop()
    .replace(/\\.[^.]+$/, '')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 60) || 'asset';
}

export async function sha256(file) {
  if (!globalThis.crypto?.subtle) throw new Error('SHA-256 requires a secure browser context.');
  const buffer = await file.arrayBuffer();
  const digest = await crypto.subtle.digest('SHA-256', buffer);
  return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, '0')).join('');
}

export function normaliseRelativePath(value) {
  return String(value || '').replace(/\\/g, '/').replace(/^\.\//, '').replace(/^\/+/, '');
}

export function makeAssetId(packId, fileName, index = 0) {
  const prefix = String(packId || 'pn.pack.custom').replace(/^pn\\.pack\\./, '');
  return `pn.${prefix}.${slugify(fileName)}${index ? '_' + index : ''}`;
}

export function validateLicence(licenceRef, approvedLicences) {
  const ref = String(licenceRef || '').trim();
  if (!ref) return { ok: false, status: 'MISSING', message: 'Licence reference is required.' };
  const record = approvedLicences?.[ref];
  if (!record) return { ok: false, status: 'REVIEW', message: 'Licence reference is not on the approved list.' };
  if (record.redistributable !== true) return { ok: false, status: 'BLOCKED', message: 'Licence is not cleared for redistribution.' };
  return { ok: true, status: 'APPROVED', message: record.name || ref };
}

export function validateManifest(manifest, approvedLicences = {}) {
  const errors = [];
  if (!/^pn\\.pack\\.[a-z0-9._-]+$/.test(manifest.id || '')) errors.push('Pack ID must match pn.pack.*.');
  if (!manifest.version) errors.push('Pack version is required.');
  if (!['core','quality','world','dlc','platform'].includes(manifest.type)) errors.push('Invalid pack type.');
  if (!['install-time','optional','on-demand','dlc'].includes(manifest.installPolicy)) errors.push('Invalid install policy.');
  if (!Array.isArray(manifest.platforms) || !manifest.platforms.length) errors.push('At least one platform is required.');
  if (!Array.isArray(manifest.dependencies)) errors.push('Dependencies must be an array.');
  if (!Array.isArray(manifest.assets)) errors.push('Assets must be an array.');

  const ids = new Set();
  for (const asset of manifest.assets || []) {
    if (!asset.id || !asset.path || !asset.type || !asset.licenceRef) errors.push(`Incomplete asset record: ${asset.id || asset.path || 'unknown'}`);
    if (ids.has(asset.id)) errors.push(`Duplicate asset ID: ${asset.id}`);
    ids.add(asset.id);
    if (asset.redistributable !== true) errors.push(`Asset is not marked redistributable: ${asset.id}`);
    const licence = validateLicence(asset.licenceRef, approvedLicences);
    if (!licence.ok) errors.push(`${asset.id}: ${licence.message}`);
    if (!/^[a-f0-9]{64}$/.test(asset.sha256 || '')) errors.push(`Missing/invalid SHA-256: ${asset.id}`);
  }
  return { valid: errors.length === 0, errors };
}

export async function createAssetRecords(files, options = {}) {
  const packId = options.packId || 'pn.pack.mansion';
  const licenceRef = options.licenceRef || 'PROJECT-NIGHTMARE-ORIGINAL';
  const records = [];
  const seen = new Map();

  for (const file of files) {
    const relativePath = normaliseRelativePath(file.relativePath || file.webkitRelativePath || file.name);
    const base = slugify(relativePath);
    const count = (seen.get(base) || 0) + 1;
    seen.set(base, count);
    records.push({
      id: makeAssetId(packId, relativePath, count > 1 ? count : 0),
      path: relativePath,
      type: classifyPackAsset(file),
      redistributable: true,
      licenceRef,
      sha256: await sha256(file)
    });
  }
  return records;
}

export function buildManifest(options, assets) {
  return {
    id: options.packId,
    version: options.version || '0.1.0',
    type: options.type || 'world',
    installPolicy: options.installPolicy || 'optional',
    platforms: options.platforms || ['web','windows','android'],
    dependencies: options.dependencies || ['pn.pack.core'],
    assets,
    notes: options.notes || 'Generated by Project Nightmare Asset Pack Builder.'
  };
}

export async function collectDirectoryFiles(directoryHandle, prefix = '') {
  const files = [];
  for await (const [name, handle] of directoryHandle.entries()) {
    const relative = prefix ? `${prefix}/${name}` : name;
    if (handle.kind === 'file') {
      const file = await handle.getFile();
      file.relativePath = relative;
      files.push(file);
    } else if (handle.kind === 'directory') {
      files.push(...await collectDirectoryFiles(handle, relative));
    }
  }
  return files;
}

async function writeText(directoryHandle, path, textContent) {
  const parts = normaliseRelativePath(path).split('/').filter(Boolean);
  const fileName = parts.pop();
  let current = directoryHandle;
  for (const part of parts) current = await current.getDirectoryHandle(part, { create: true });
  const handle = await current.getFileHandle(fileName, { create: true });
  const writable = await handle.createWritable();
  await writable.write(textContent);
  await writable.close();
}

async function writeFile(directoryHandle, path, file) {
  const parts = normaliseRelativePath(path).split('/').filter(Boolean);
  const fileName = parts.pop();
  let current = directoryHandle;
  for (const part of parts) current = await current.getDirectoryHandle(part, { create: true });
  const handle = await current.getFileHandle(fileName, { create: true });
  const writable = await handle.createWritable();
  await writable.write(file);
  await writable.close();
}

export async function buildPackToDirectory(destinationHandle, manifest, files) {
  const packFolder = await destinationHandle.getDirectoryHandle(
    manifest.id.replace(/^pn\\.pack\\./, ''),
    { create: true }
  );
  await writeText(packFolder, 'manifest.json', JSON.stringify(manifest, null, 2));
  for (const file of files) await writeFile(packFolder, file.relativePath || file.name, file);
  return packFolder;
}

export function downloadJson(filename, data) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
